### ISSUE TITLE
Is the web UI supposed to look like this?

### ISSUE THREAD

**Issue by Netherdrake** [metachaos-systems/glasnost#17]
![screenshot from 2017-10-11 00-40-00](https://user-images.githubusercontent.com/3516903/31414138-cb50851e-ae1c-11e7-9f87-9d99dfd56f85.png)

Seems a bit off. Running on `master` head.

**Comment by ontofractal** [comment]
Nope, not really :) This is a leftover from a time when Glasnost was a static HTML server and didn't have GraphQL API. Will be updated in the next releases.
